### ISSUE TITLE
ZLIB missing for Windows x64

### ISSUE THREAD

**Issue by DennisGerritsenCloudflight** [MyUnisoft/heif-converter#25]
Hey,

I've encountered that the library does not seem to work on runtime for Windows due to the ZLIB dll missing. I managed to fix the issue by simply supplying the ZLIB dll as well next to the other dlls. Would be cool if a fix will be provided :).

**Comment by Dafyh** [comment]
Hello 👋 !

Indeed, if it's not the default on the Windows machine, it doesn't work.

I'll change it as soon as possible 😊.

**Comment by DennisGerritsenCloudflight** [comment]
Thanks a lot :)

**Comment by Dafyh** [comment]
Hello 👋

A new version has just been released with zlib.dll for windows. I'll let you close the issue in case it's OK for you, or come back to me if you still have a problem👌.
